name: Pull Request Workflow

on:
  pull_request:
    branches:
      - developer/v1.0
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  pr-job:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate Short SHA
      - name: Set Short SHA
        id: short-sha-step
        run: |
          FULL_SHA=${{ github.event.pull_request.head.sha }}
          SHORT_SHA=${FULL_SHA:0:7}
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "Generated Short SHA: $SHORT_SHA"

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Install Trivy
      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.2.2
        with:
          version: v0.65.0
          cache: true

      # ---------------- ORDER SERVICE ----------------

      - name: Build order service image
        uses: docker/build-push-action@v6
        with:
          context: ./src/order-service
          load: true
          tags: order-service:${{ steps.short-sha-step.outputs.SHORT_SHA }}

      - name: Scan order service image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: order-service:${{ steps.short-sha-step.outputs.SHORT_SHA }}
          format: sarif
          output: order-trivy-results.sarif

      # ---------------- PRODUCT SERVICE ----------------

      - name: Build product service image
        uses: docker/build-push-action@v6
        with:
          context: ./src/product-service
          load: true
          tags: product-service:${{ steps.short-sha-step.outputs.SHORT_SHA }}

      - name: Scan product service image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: product-service:${{ steps.short-sha-step.outputs.SHORT_SHA }}
          format: sarif
          output: product-trivy-results.sarif

      # ---------------- STORE FRONT ----------------

      - name: Build store front image
        uses: docker/build-push-action@v6
        with:
          context: ./src/store-front
          load: true
          tags: store-front:${{ steps.short-sha-step.outputs.SHORT_SHA }}

      - name: Scan store front image
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: store-front:${{ steps.short-sha-step.outputs.SHORT_SHA }}
          format: sarif
          output: store-trivy-results.sarif
