name: Pull Request Workflow

on:
  pull_request:
    branches:
      - developer/v1.0
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  pr-job:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Generate Short SHA
      - name: Set Short SHA
        id: short-sha-step
        run: |
          FULL_SHA=${{ github.event.pull_request.head.sha }}
          SHORT_SHA=${FULL_SHA:0:7}
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT
          echo "Generated Short SHA: $SHORT_SHA"

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ---------------- ORDER SERVICE ----------------

      - name: Build order service image
        run: |
          docker build \
          -t order-service:${{ steps.short-sha-step.outputs.SHORT_SHA }} \
          ./src/order-service

      - name: Scan order service image
        run: |
          trivy image --severity HIGH,CRITICAL \
          order-service:${{ steps.short-sha-step.outputs.SHORT_SHA }}

      # ---------------- PRODUCT SERVICE ----------------

      - name: Build product service image
        run: |
          docker build \
          -t product-service:${{ steps.short-sha-step.outputs.SHORT_SHA }} \
          ./src/product-service

      - name: Scan product service image
        run: |
          trivy image --severity HIGH,CRITICAL \
          product-service:${{ steps.short-sha-step.outputs.SHORT_SHA }}

      # ---------------- STORE FRONT ----------------

      - name: Build store front image
        run: |
          docker build \
          -t store-front:${{ steps.short-sha-step.outputs.SHORT_SHA }} \
          ./src/store-front

      - name: Scan store front image
        run: |
          trivy image --severity HIGH,CRITICAL \
          store-front:${{ steps.short-sha-step.outputs.SHORT_SHA }}